# application.properties

spring.datasource.url=jdbc:mysql://localhost:3306/fleet_db
spring.datasource.username=root
spring.datasource.password=3535

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.main.web-application-type=servlet
spring.jpa.properties.hibernate.boot.model.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jackson.deserialization.fail-on-unknown-properties=false

#GraphHopper Api
graphhopper.api.key=c3b24383-8feb-4bc5-9dd7-1349fd4495fa
graphhopper.api.base-url=https://graphhopper.com/api/1/matrix
graphhopper.api.timeout-seconds=30
graphhopper.api.enable=true
graphhopper.api.use-fallback=true
